### ISSUE TITLE
Support Kotlin-only projects

### ISSUE THREAD

**Issue by rverma-jm** [porscheinformatik/sonarqube-licensecheck#215]
Trying to use the plugin with sonarqube 8.5 community.

Tried multiple inputs with sonar-scanner like

`-Dlicensecheck.licenses=./bifrost/build/reports/dependency-license/index.html`
`-Dlicensecheck.projectlicenses=./bifrost/build/reports/dependency-license/index.html`
`-Dlicensecheck.licenses=./bifrost/build/reports/dependency-license/index.json`    

etc, but none of them reflected any result on sonarqube dashboard. The xml/json files are generated with right data though.

**Comment by rverma-jm** [comment]
Realized that the rule is only available for Java Language and not for Kotlin. Although we are using gradle and I believe we this module should be compatible, I think it may need some tweak to make sure that this profile is available for kotlin too.

**Comment by Janpopan** [comment]
You can add a simple and unused java file to your project, than the rules will be activate.

**Comment by oliverlockwood** [comment]
@rverma-jm FYI issue #182 has more context around this.

**Comment by ffuf-schweizer** [comment]
Hey! Did I miss something? Tried the gradle setup and it does not seem to work on my side out of the box. The license check page was always empty. Had to adjust the following part, rebuilt the plugin and it worked:

![image](https://user-images.githubusercontent.com/79456487/155375337-bde17f42-1590-4959-a7a2-614ab1061778.png)

Not quite sure if this might have too much impact and if I'm doing something wrong here since noone else complained yet? Am using SonarQube 9.3 and license check plugin 5.0.0. Besides the small adjustment it seems running smooth with 9.3, haven't tested 9.2 and older yet therefore.
