### ISSUE TITLE
No license check with npm, empty?

### ISSUE THREAD

**Issue by axi92** [porscheinformatik/sonarqube-licensecheck#314]
Did I miss something on the setup or settings?
I am running the sonar-scanner on an node project with npm and there is nothing checked.
Can I check some logs to get a better understanding whats happening? Scan log shows nothing and background task log also nothing significant.
![image](https://user-images.githubusercontent.com/1394837/155992053-544dcaa2-99b1-45e2-8980-b47a19820af0.png)

Sonar: Version 8.9 (build 43852)
"sonarqube-scanner": "^2.8.1"
sonarqube-licensecheck Plugin: 5.0.1

**Comment by rdsubhas** [comment]
Hi, probably one of two things:

1. Just in case, check if the project is recognized as a `typescript` project. This plugin does not activate for typescript (solved by #315). But I assume that's not the problem here, see next.
2. The `Quality Profile` that you use for scanning this project – it needs to have `license-check` rules **Activated**. Sonarqube won't do this by default, you have to activate it in the quality profile.

**Comment by axi92** [comment]
Ok thank you for the hint, but I cant find anything about license in the rules?

**Comment by Xeyos88** [comment]
I re-open this issue because I have the same problem.
I have sonar.sources on src folder.
I added license rules in quality profile, analysis used the profiler with the updated rules but no license in the screen.

My version of SonarQube is 9.9

**Comment by Janpopan** [comment]
Can you provide some information about your project type and structure?
