### ISSUE TITLE
Plugin 2.0x not scanning licenses with SonarQube v6.7.1 docker image

### ISSUE THREAD

**Issue by ishaks09** [porscheinformatik/sonarqube-licensecheck#33]
We are using SonarQube v6.7.1 alpine docker image to scan our current projects. Our plugin installation and server restart were successful. 

We enabled the licenses globally by changing them to 'true' under configuration>license check option. And we activated the rules under quality profile. now when we scan any of Java, JavaScript, Maven projects that have LICENSE.md / LICENSE.txt file at root level in the repo, we don't see the 'Dependencies' and 'Licenses' table populated in Project dashboard > More > License check.

Are we supposed to enable any other configuration? or is there a format expected for licenses to be written in the .md/.txt files? Any help appreciated!

**Comment by derkoe** [comment]
First of all - don't use SonarQube 6.7.1! Switch to the current bugfix version (currently 6.7.6).

This plugin does not read license text files - it doese the license recognition by reading the dependencies of your application via pom.xml (Java) or package.json (JavaScript). For package.json the license recognition works out of the box (since it uses SPDX format). For Maven projects you have to define mappings between license name or groupId/artifactId under Configuration > License Check > Maven Dependencies and Licenses.
