### ISSUE TITLE
New Release for version 10 compatibility

### ISSUE THREAD

**Issue by Breee** [porscheinformatik/sonarqube-licensecheck#383]
According to https://github.com/porscheinformatik/sonarqube-licensecheck/issues/373 everything necessary for  Sonar version 10 compatibility exists. 

When can we expect a release?  There are bugs in Sonarqube 9.x LTS for us that would be fixed by upgrading to version 10.1+  

Kind Regards

**Comment by fvclaus** [comment]
@Breee , there is https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v6.0.0-alpha-1 which can be installed manually. I guess is @derkoe is waiting for feedback? At the company I work, we are running a identical version (I build it myself, because I needed it earlier) without problems for probably 3 months now.

**Comment by Breee** [comment]
We have completely automated our plugin updates, so building the package ourselves it not an option (at least not without building extra logic to handle this plugin). If @derkoe provides information what needs to be tested and what feedback he needs, maybe we can provide it somehow.

**Comment by derkoe** [comment]
@Breee the pre-release is built - no need for building. Jjust replace the version: https://github.com/porscheinformatik/sonarqube-licensecheck/releases/download/v6.0.0-alpha-1/sonarqube-licensecheck-plugin-6.0.0-alpha-1.jar

Check if everything is working for you and report back here https://github.com/porscheinformatik/sonarqube-licensecheck/discussions/378

**Comment by muellerst-hg** [comment]
Successfully tested 6.0.0-beta2 with Sonar 10.3
